[package]
name = "rust-ffi-example"
version = "0.1.0"
authors = ["Mingwei Zhang <mingwei@mwzhang.com>"]
edition = "2018"

[lib]
name="bgpstream"
# crate-type=["staticlib"]

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.42.2"
cc = "1.0"
