[package]
name = "rust-ffi-example"
version = "0.1.0"
authors = ["Mingwei Zhang <mingwei@mwzhang.com>"]
edition = "2018"

[lib]
name="ffi"
crate-type=["staticlib"]

[build-dependencies]
bindgen = "0.42.2"
